### ISSUE TITLE
slm 3likm 

### ISSUE THREAD

**Issue by fcb4355** [Chargily/chargily-pay-javascript#4]
problem Que ki ndir 

import { ChargilyClient } from '@chargily/chargily-pay';

ykhrjli prblm li howa hada 

Uncaught SyntaxError: Cannot use import statement outside a module

w ki drt type = "module"

ykhrli hadi 

Uncaught TypeError: Failed to resolve module specifier "@chargily/chargily-pay". Relative references must start with either "/", "./", or "../".

Chofna hal svpl

**Comment by ruzolut** [comment]
To ensure we can effectively assist you, please follow these guidelines when reporting an issue:

- Title: Clearly summarize the problem in a few words.
- Environment Details: Include specifics like your operating system, Node.js version, and library version (@chargily/chargily-pay).
- Steps to Reproduce: Detail the exact steps that led to the problem. Include code snippets or commands you ran.
- Expected vs. Actual Behavior: Describe what you expected to happen and what actually occurred.
- Error Messages: Include any error messages or stack traces.
- Attempted Solutions: Mention any steps you've taken to try and solve the issue.

A well-structured issue helps us diagnose and address your problem more quickly.

This [article](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f) on writing a good issue could also help.

Looking forward to assist you.

**Comment by fcb4355** [comment]
wch mn details khoya rani ki ndir hadi  import { ChargilyClient } from '@chargily/chargily-pay';  ykhrjli prblm f console w rani dyr last version ta3 node js w meme problem

**Comment by fcb4355** [comment]
```
import { ChargilyClient } from '@chargily/chargily-pay';

const client = new ChargilyClient({
  api_key: 'test_sk_xxxx',
  mode: 'test', 
});
```

Hada howa Error li ykhrjli f console malgre rani dyr la dernier version ta3 node js


`Uncaught SyntaxError: Cannot use import statement outside a module (at app.js:1:1)`

**Comment by ruzolut** [comment]
> ```
> import { ChargilyClient } from '@chargily/chargily-pay';
> 
> const client = new ChargilyClient({
>   api_key: 'test_sk_xxxx',
>   mode: 'test', 
> });
> ```
> 
> Hada howa Error li ykhrjli f console malgre rani dyr la dernier version ta3 node js
> 
> 
> `Uncaught SyntaxError: Cannot use import statement outside a module (at app.js:1:1)`
> 
> 

Try to import the package like this:
```js
const { ChargilyClient } = require('@chargily/chargily-pay')
```

And there is no need to set workspace type to module in your package.json file.

PS: this is not an issue with the Chargily library, it's JavaScript and Node.JS related, I advise you to look up the error and try to debug it before opening an issue here.

Let me know if your issue is fixed,
Best of luck.

**Comment by fcb4355** [comment]
Sorry the problem Not fixed 

This error 

`app.js:1 Uncaught ReferenceError: require is not defined`

**Comment by ruzolut** [comment]
@fcb4355 can you please provide these:
- Your operating system information.
- Node version that you are using.
- A screenshot of your project's folder structure (On your code editor).
- Your full `package.json` file.

**Comment by t-88** [comment]
i got the same problem but after setting   **type : "module"** in package.json, it works fine
make sure u type **":"** and not **"="**  in type : "module". like this
![image](https://github.com/Chargily/chargily-pay-javascript/assets/89593218/27334348-2d85-4eaa-b1b2-0a809e14d38a)

**Comment by fcb4355** [comment]
![hhhhh](https://github.com/Chargily/chargily-pay-javascript/assets/116302980/fd902a2a-0923-4970-8230-43f64ed365e2)

**Comment by fcb4355** [comment]
@rofazayn 

Window 10 pro 
node js version talya drtlha update doka 
w screen hadhi
![hhhhh](https://github.com/Chargily/chargily-pay-javascript/assets/116302980/c2fce2c5-958b-44bd-9af8-006944d38de6)

**Comment by fcb4355** [comment]
![nnnnn](https://github.com/Chargily/chargily-pay-javascript/assets/116302980/f3369649-cb7e-4c79-8e08-ce429743f18d)

**Comment by ruzolut** [comment]
I'm closing this issue and marking it as irrelevant because it's not an issue with the library itself, it's just that you are not implementing it the right way.

Please do your own research on how you can use NPM modules directly in your browser, which I do not recommend for this particular library because it could raise significant security vulnerabilities.

A little hint, you could have a look at `browserify`.

Thank you
